---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: grafana
spec:
  chart:
    spec:
      chart: grafana-operator
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  targetNamespace: grafana
  interval: 24h0m0s
  values:
    namespaceScope: false 
    replicas: 1
