---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: version-checker
  namespace: version-checker
spec:
  chart:
    spec:
      chart: version-checker
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: jetstack
  targetNamespace: version-checker
  interval: 24h0m0s
