---
#
# This configuration bootstraps a private Certificate Authority for
# use inside a local minikuibe cluster. Because the cluster does not
# control any public IP or DNS records, it does not make sense to rely
# on a public Certificate Authority. Instead, we create a self-signed
# root CA and then configure cert-manager to use that CA to issue
# certificates for in-cluster services. This ensures we can issue TLS
# certificates as needed, without any external dependencies.
#
# This process has three steps: first we create a temporary
# self-signed issuer which is used only to generate the root CA.
# Second, we define the root CA certificate itself, which will be
# stored as a Kubernetes secret. Third, we create a ClusterInssuer
# that references the root CA secret and can then be used by
# applications or Ingress resources to request signed leaf
# certificates.
#

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: root-ca
  secretName: root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-ca
