---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: version-checker-install
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./infra/version-checker/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: jetstack-install
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: version-checker-resources
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./infra/version-checker/resources
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: version-checker-install
      namespace: flux-system
