---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: install
  namespace: version-checker
spec:
  interval: 1h0m0s
  path: ./infra/version-checker/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: jetstack
      namespace: jetstack
