---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api
  - cilium
  - cert-manager
  - local-path-provisioner
  - istio
  - opentelemetry
  - prometheus
  - kiali
  - jaeger
  - external-secrets
  - jetstack
  - kyverno
  - tetragon
