---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium
      version: 1.18.3
  targetNamespace: kube-system
  interval: 24h0m0s
  values:
    kubeProxyReplacement: true
    k8sServiceHost: auto
    k8sServicePort: 8443
    l2announcements:
      enabled: true
    devices:
      - eth0
    gatewayAPI:
      enabled: true
    l7Proxy: true
    envoy:
      enabled: true
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
            - NET_BIND_SERVICE
            - NET_ADMIN
            - SYS_ADMIN
    cni:
      exclusive: false
    socketLB:
      enabled: true
      hostNamespaceOnly: true
    operator:
      replicas: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true 
