---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: opentelemetry
spec:
  interval: 24h0m0s
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
