---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sslyze
spec:
  chartRef:
    kind: OCIRepository
    name: sslyze
  interval: 24h0m0s
  values:
    parser:
      image:
        tag: 5.1.0
      ttlSecondsAfterFinished: 10
    scanner:
      image:
        tag: 6.2.0
      ttlSecondsAfterFinished: 10
