---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: install
  namespace: securecodebox
spec:
  interval: 1h0m0s
  path: ./infra/securecodebox/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

