---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: install
  namespace: prometheus
spec:
  interval: 1h0m0s
  path: ./infra/prometheus/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: prometheus
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: resources
#  namespace: prometheus
#spec:
#  interval: 10m0s
#  path: ./infra/prometheus/resources
#  prune: true
#  wait: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  dependsOn:
#    - name: install
#      namespace: prometheus
