---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zap
spec:
  interval: 24h0m0s 
  url: oci://ghcr.io/securecodebox/helm/zap-automation-framework
  ref:
    tag: 5.1.0
